version: '2.1'
services:
  database:
    restart: always
    image: postgres:10.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=backend
      - POSTGRES_DB=insurance
    volumes:
      - ./insurance_db:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    expose:
      - '5433'
  britecore:
    restart: always
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - .:/britecore
    environment:
      DATABASE_URI: postgres://postgres:backend@database:5432/insurance
    depends_on:
      - database
    entrypoint: ["/bin/bash","-c","/britecore/docker/start_api.sh"]
    stdin_open: true
    tty: true
